etcd:
  image: quay.io/coreos/etcd:v2.0.8
  command: -name bastion_etcd -advertise-client-urls http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 -initial-advertise-peer-urls http://127.0.0.1:2380 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token opsee -initial-cluster bastion_etcd=http://127.0.0.1:2380 -initial-cluster-state new
  ports:
    - 2379:2379
nsqd:
  image: nsqio/nsq:v0.3.5
  command: /nsqd
  ports:
    - 4150:4150
    - 4151:4151
nsqadmin:
  image: nsqio/nsq:v0.3.5
  command: /nsqadmin -nsqd-http-address=nsqd:4151
  links:
    - nsqd:nsqd
slate:
  image: quay.io/opsee/slate
  ports:
    - 7000:7000
